name: "1. Run Jmeter test plan"

on: workflow_dispatch

jobs:
  connect_ssh:
    name: Run Jmeter test plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        
      - name: Connect to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_TESTING_DNS }}
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user

      - name: Run Jmeter
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_TESTING_DNS }}
          username: ec2-user
          port: 22 
          script: bash run_jmeter_script.sh -u 10 -i 4 -a ${{ secrets.AWS_APPLICATION_DNS }} -s 4
