name: "1. Run Jmeter test plan"

on: workflow_dispatch

jobs:
  connect_ssh:
    name: Run Jmeter test plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Connect and run jmeter
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_TESTING_DNS }}
          username: ec2-user
          port: 22 
          script: | 
           docker run --name jmeter -v First_tests.jmx:/mnt/jmeter/First_tests.jmx:ro justb4/jmeter:latest \
           -n -t /mnt/jmeter/First_tests.jmx -Jurl=${{ secrets.AWS_APPLICATION_DNS }} -l /mnt/jmeter/results.csv 
