name: "1. Run Jmeter test plan"

on:
  workflow_dispatch:
    inputs:
      users:
        description: 'Users'     
        required: true
      iterations:
        description: 'Iterations'     
        required: true
      sleep:
        description: 'Sleep'     
        required: true

jobs:
  connect_ssh:
    name: Run Jmeter test plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        
      - name: Connect to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_TESTING_DNS }}
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user

      - name: Run Jmeter
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_TESTING_DNS }}
          username: ec2-user
          port: 22 
          command_timeout: 60m
          script: bash run_jmeter_script.sh -u ${{ github.event.inputs.users }} -i ${{ github.event.inputs.iterations }} -a ${{ secrets.AWS_APPLICATION_DNS }} -s ${{ github.event.inputs.sleep }}
